version: '3.8'

networks:
  internal:
  proxy:
    external: true

services:

  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      #      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy

  db:
    image: mariadb:10.11.2
    container_name: db
    restart: always
    labels:
      - "traefik.enable=false"
    environment:
      MYSQL_ROOT_PASSWORD: QT6e5APtSYaU
      MYSQL_USER: root
      MYSQL_PASSWORD: QT6e5APtSYaU
      MYSQL_DATABASE: sfp_macaron_db
    volumes:
      - ./db:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 15432:80
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.sfp-macaron.develop`)"
    environment:
      UPLOAD_LIMIT: 300M
    networks:
      - internal
      - proxy

  app:
    container_name: app
    restart: always
    build:
      context: ./docker
    depends_on:
      - db
    labels:
      - "traefik.enable=false"
    environment:
      - APP_ENV=dev
      - XDEBUG_MODES=debug
      - TZ=Africa/Abidjan
      - DATABASE_URL=mysql://root:QT6e5APtSYaU@db:3306/sfp_macaron_db?serverVersion=14
      - REMOTE_HOST=host.docker.internal
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www/html
    networks:
      - internal

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=Host(`sfp-macaron.develop`)"
      - "traefik.http.services.www.loadbalancer.server.port=80"
    depends_on:
      - app
    networks:
      - internal
      - proxy

