version: '3.8'

networks:
  internal:
  proxy:
    external: true

services:

  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: QT6e5APtSYaU
      MYSQL_USER: root
      MYSQL_PASSWORD: QT6e5APtSYaU
      MYSQL_DATABASE: sfp_macaron_db
    volumes:
      - ./database:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    networks:
      - internal
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      UPLOAD_LIMIT: 300M
    networks:
      - internal
      - proxy
    ports:
      - 83:80

  app:
    container_name: app
    restart: always
    build:
      context: ./docker
    depends_on:
      - db
    environment:
      - APP_ENV=prod
      - TZ=Africa/Abidjan
      - DATABASE_URL=mysql://root:QT6e5APtSYaU@db:3306/sfp_macaron_db?serverVersion=14
    volumes:
      - ./codebase:/var/www/html
    networks:
      - internal

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./codebase:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - internal
      - proxy
    ports:
      - 82:80
