knp_snappy:
  pdf:
    enabled: true
    binary:  '%kernel.project_dir%/bin/wkhtmltopdf-amd64'
    options: [ ]

  image:
    enabled:    true
    binary:     '%kernel.project_dir%/bin/wkhtmltoimage-amd64'
    options:    []

  temporary_folder: "%kernel.cache_dir%/snappy"
