#vich_uploader:
#  db_driver: orm
#
#  metadata:
#    type: attribute
#
#  mappings:
#    application:
#      uri_prefix: /application/documents
#      upload_destination: '%kernel.project_dir%/public/applications/documents'
#      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer